name: Docker

on:
  push:
    branches: [ master ]  

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Build and push Docker image and publish to github packages
        run: 
         VERSION=$(date +%s) 
         docker build . --file Dockerfile --tag docker.pkg.github.com/rahuld78/sample/app:${VERSION}
         docker login docker.pkg.github.com --username Rahul-D78 --password ${{secrets.GITHUB_TOKEN}}
         docker push docker.pkg.github.com/rahuld78/sample/app:${VERSION}
